
@baseUrl = http://localhost:4000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJJZCI6IjY2ZGU4Yzc4ODgyOWNhMjRjNTAxZmY1YSIsImVtYWlsIjoicmFuaWFAZ21haWwuY29tIn0sImlhdCI6MTcyNzg2MTQxNSwiZXhwIjoxNzI3ODY4NjE1fQ.aeCwuXTuCi931D87XF6Tdoe8cds2I9oqftzVJsY6hx8
PUT  {{baseUrl}}/comments/66edaf7ce007898642009928
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "ccc modifié"
}